name: Vérification du respect des spécifications

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Installation Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Installation des dépendances
      run: pip install -r requirements.txt
    - name: Vérification du schéma site et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema site/schema.json
    - name: Vérification du schéma channel et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema channel/schema.json
    - name: Vérification du schéma measure et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema measure/schema.json
    - name: Vérification du datapackage
      run: |
        frictionless validate datapackage.json