name: Vérification du respect des spécifications

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Installation des dépendances
      run: pip install -r requirements.txt
    - name: Vérification du schéma site et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema site/schema.json
        frictionless validate --schema site/schema.json site/exemple-valide.csv
        frictionless validate --schema site/schema.json site/exemple-valide-eco-compteur.csv
    - name: Vérification du schéma channel et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema channel/schema.json
        frictionless validate --schema channel/schema.json channel/exemple-valide.csv
        frictionless validate --schema channel/schema.json channel/exemple-valide-eco-compteur.csv
    - name: Vérification du schéma measure et des fichiers d'exemples associés
      run: |
        frictionless validate --type schema measure/schema.json
        frictionless validate --schema measure/schema.json measure/exemple-valide.csv
        frictionless validate --schema measure/schema.json measure/exemple-valide-eco-compteur.csv
    - name: Vérification du datapackage
      run: |
        frictionless validate datapackage.json
